apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
spec:
  containers:
  - name: inspector
    image: busybox
    command: ["sh", "-c", "ls -R /data && sleep 3600"]
    volumeMounts:
    - name: my-data
      mountPath: /data
  volumes:
  - name: my-data
    persistentVolumeClaim:
      claimName: oidc-pvc # Use your actual PVC name here
