apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: oidc-final-victory-run
  namespace: my-onboarding-project
spec:
  pipelineRef:
    name: github-refresh-pipeline
  serviceAccountName: tekton-aws-sa
  workspaces:
  - name: shared-data
    persistentVolumeClaim:
      claimName: hello-python-pvc
  podTemplate:
    volumes:
      - name: oidc-token-vol
        secret:
          secretName: aws-oidc-token
    env:
      - name: AWS_ROLE_ARN
        value: arn:aws:iam::319310747432:role/GitHubAction-AssumeRoleWithAction
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/aws/token
      - name: AWS_REGION
        value: us-east-1
    volumeMounts:
      - name: oidc-token-vol
        mountPath: /var/run/secrets/aws
        readOnly: true
